# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Lauren Watson
tagline:          'Phd Candidate - Privacy Preserving Machine Learning'
description:      'University of Edinburgh'
url:              laurenwatson.github.io
baseurl:          /

author:
  name:           'Lauren Watson'
  url:            https://twitter.com/Lauren_R_Watson

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/laurenwatson/laurenwatson.github.io
